"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_dir_first = true
# show_hidden = true

[opener]
folder = [
  { run = 'open -R "$1"', desc = "GUI file manager" },
  # { run = '''fish -c "nvim "$1""''', block = true, desc = "neovim", for = "macos" },
  # { run = 'kitty --detach nvim "$@"', orphan = true, desc = "neovim (detached)", for = "macos" },
  # { run = '''fish -c "lazygit -p "$1""''', block = true, desc = "lazygit", for = "macos" },
  # { run = 'code  "$@"', orphan = true, desc = "vscode", for = "macos" },
  # { run = 'kitty "$@"', orphan = true, desc = "kitty", for = "macos" },
]

text = [
  { run = 'nvim "$@"', block = true, desc = "neovim", for = "unix" },
  { run = 'kitty --detach nvim "$@"', block = true, desc = "neovim (detached)", for = "macos" },
  { run = 'code "$@"', orphan = true, desc = "vscode", for = "macos" },
  { run = 'open "$@"', orphan = true, desc = "open", for = "macos" },
]

document = [
  { run = 'open "$@"', orphan = true, desc = "open", for = "macos" },
]

image = [
  { run = 'open "$@"', orphan = true, desc = "open", for = "macos" },
]
video = [
  { run = 'open "$@"', orphan = true, desc = "open", for = "macos" },
]
audio = [
  { run = 'open "$@"', orphan = true, desc = "open", for = "macos" },
]
fallback = [
  { run = 'open "$@"', orphan = true, desc = "open", for = "macos" },
]

[open]
rules = [
  { name = "*/", use = "folder" },

  { mime = "text/*", use = "text" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "video" },
  { mime = "application/octet-stream", use = "video" },
  { mime = "audio/*", use = "audio" },
  { mime = "inode/x-empty", use = "text" },
  { mime = "application/json", use = "text" },

  { mime = "application/zip", use = "archive" },
  { mime = "application/gzip", use = "archive" },
  { mime = "application/x-bzip", use = "archive" },
  { mime = "application/x-bzip2", use = "archive" },
  { mime = "application/x-tar", use = "archive" },
  { mime = "application/x-7z-compressed", use = "archive" },
  { mime = "application/x-rar", use = "archive" },
  { mime = "application/pdf", use = "document" },
  { mime = "application/epub+zip", use = "document" },
  { mime = "application/x-mobipocket-ebook", use = "document" },

  { mime = "*", use = "fallback" },
]
