require("items.apple")
require("items.spaces")
-- require("items.menus")
-- require("items.switch")
require("items.front_app")
require("items.calendar")
require("items.widgets")
-- require("items.media")
