#!/bin/bash

# Apps
# spotify &
# vesktop &
# thunderbird &
# obsidian &
clash-verge &

# Terminal Apps
# kitty --class btop btop &
# kitty --class cava cava &
# kitty --class pipes pipes &
# kitty --class tty-clock tty-clock -sbc &
# kitty --class nvtop nvtop &


