# Configs
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/binds.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/workspaces.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/misc.conf
source = ~/.config/hypr/plugins/hycov.conf

# Theme (Add the theme you want)
source = ~/.config/hypr/themes/luna/luna.conf

# Autostart
exec-once = $HOME/.config/hypr/scripts/autostart/services
exec-once = $HOME/.config/hypr/scripts/autostart/apps
# exec-once = $HOME/.config/hypr/scripts/clipboard

# Input method
exec-once=fcitx5-remote -r
exec-once=fcitx5 -d --replace

# Clipboard
exec-once = cb

# Menu Bar
exec-once = agsv1

# Hyprland plugins management
# exec-once = hyprpm update -v
exec-once = hyprswitch init --custom-css $HOME/.config/hyprswitch/theme.css --show-title --size-factor 3 --workspaces-per-row 5 &
