# Configs
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/binds.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/workspaces.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/misc.conf

# Theme (Add the theme you want)
source = ~/.config/hypr/themes/luna/luna.conf

# Autostart
exec-once = $HOME/.config/hypr/scripts/autostart/services
exec-once = $HOME/.config/hypr/scripts/autostart/apps

exec-once=fcitx5-remote -r
exec-once=fcitx5 -d --replace
exec-once=fcitx5-remote -r


# exec-once = swayidle -w timeout 300 'swaylock -f' timeout 600 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' before-sleep 'swaylock -f' 




# Plugins (Uncomment this line if you are going to use the plugins)
# exec-once = hyprpm reload -n
